# Generated by scripts/update.sh from Valve's client manifest. Do not edit.
{
  channel = "publicbeta";
  version = "1790721607";
  baseUrl = "https://client-update.fastly.steamstatic.com";
  components = {
    tenfoot_images_all = {
      file = "tenfoot_images_all.zip.86419c7a56c12dd107b5e0d46f50c8a9b121f3cc";
      sha256 = "990676bc29d01736477c6b571b5048258a6156284ef242503112fc68567cbf01";
    };
    steamui_websrc_all = {
      file = "steamui_websrc_all.zip.9d0ea13790db7d3ff6185a3bec87c7888b99a375";
      sha256 = "d641fbcb374b1f23ac1f05176db93595548cf7e3ae441f21d4fc1a1e6421a060";
    };
    resources_misc_all = {
      file = "resources_misc_all.zip.99ed79ed868d732d8e9e9a45444b8f003191e3dd";
      sha256 = "187e562403c7544af7162e08baf7677d030ad6f60947c2cdc7dcbcbf0a7a7fe6";
    };
    resources_hidpi_all = {
      file = "resources_hidpi_all.zip.a110d78e994c028dc1c412951e87a0c4e9c819f7";
      sha256 = "5bdb97ec734f035c1d06a59b62980028b1b05b920c544ae3673b1a515d3d507e";
    };
    resources_all = {
      file = "resources_all.zip.213fe769fd8484a0d149453c5655e70c1d13b086";
      sha256 = "769840cdb2b22ad9798a1a3950de2fe82b8b5d3d37389dcc9b1393f77480d67b";
    };
    strings_en_all = {
      file = "strings_en_all.zip.e716a67d7fa91ba70490a6417e25d45c5435e393";
      sha256 = "0c56193fac4fa518eaaac0dc66ecd21a3cee510ece85594b6c308f8d31ee98a3";
    };
    strings_all = {
      file = "strings_all.zip.ad0779a3a2612ae06fe66604b121245d3905fd12";
      sha256 = "5a5370f3b16675cc39d928d8557ff42f4f6caa427ea4d6bc7f98ee31d8ef9513";
    };
    public_all = {
      file = "public_all.zip.10426d0860e311f024654d1f932d4434e6d55a92";
      sha256 = "3cbb29584059934c95145400304319ca9a4a47d54a4978c6ecac1cfad2357847";
    };
    bins_hardware_all = {
      file = "bins_hardware_all.zip.08e06107fc29032a743211975a447189839af5a9";
      sha256 = "5b81dbc36048eb0d5b99e212e935f15f500eac1ad24998f88d4f4df1e5203c39";
    };
    steamui_websrc_sounds_all = {
      file = "steamui_websrc_sounds_all.zip.74727ca40ef88c5012bb631488fd285418dce825";
      sha256 = "c823bd39d234e7d9a5fdb5ec6605eae3f175e52bb847725e8826ff526a61641c";
    };
    steamui_websrc_movies_all = {
      file = "steamui_websrc_movies_all.zip.40e78cdda48e9a8a74baf614e0cdc7a6b96d26d1";
      sha256 = "885a32533327f0fd5ea98e6c6f13552e965cab4852dad7ce9ccf3d929d726b5b";
    };
    webkit_linuxarm64_linuxarm64 = {
      file = "webkit_linuxarm64_linuxarm64.zip.c1d5fa58a564375f71b34bccaa51c19be1143137";
      sha256 = "b8687e0f20668d24055d8f2e9f6c4fbcbe84fbb99a7bc9de4595530be7029990";
    };
    sdl3_linuxarm64_linuxarm64 = {
      file = "sdl3_linuxarm64_linuxarm64.zip.4fd0ba0265a38cd1bdb0d3e885204051797e8542";
      sha256 = "8fcc1caac5161e5f627a01f5c4e39a69d913d653c303d5c391243a3bf4222faa";
    };
    codecs_linuxarm64_linuxarm64 = {
      file = "codecs_linuxarm64_linuxarm64.zip.b27e1d78cec034a8c73b0ff1bc6acbe3b8586344";
      sha256 = "8e77a5e4605d7c7b576ce64abf39cfd342aea8d6783e17f2fb91e1c8f4357a0f";
    };
    bins_linuxarm64_linuxarm64 = {
      file = "bins_linuxarm64_linuxarm64.zip.7e5608630efa476c001328dc0c8543d9fa26f7f1";
      sha256 = "23ff7ac20d122d7c413a18751cf808d52ac278fe65d84608ec5604bf33f1de18";
    };
    bins_sdk_linuxarm64_linuxarm64 = {
      file = "bins_sdk_linuxarm64_linuxarm64.zip.7aeadfdbae1a7093bbbdf9e145903ad2ce1a24ba";
      sha256 = "4f0d8a8e51b75e2ead56322c8f1813dac00127a06ddd667189728551629cf9b7";
    };
    resource_linuxarm64_linuxarm64 = {
      file = "resource_linuxarm64_linuxarm64.zip.6e5691ac5a1a55a554250468a98c3f8e454fea4a";
      sha256 = "f78280db38d95a74096a00f7d2bc3061286db135e9e61bbf963eb65de39d66fc";
    };
  };
}
